# Set to:
# VIDEO - use video file with name VIDEO_FILE
# YT - use YouTube URL with name YT_URL
# WEBCAM - use webcam

SOURCE: "VIDEO"  # Options: "VIDEO", "YT", "WEBCAM"

VIDEO_FILE: "0vkld4n1a7o.mp4"

# example URL:
YT_URL: "https://www.youtube.com/watch?v=0vkld4n1a7o"
# Seconds into the video to start at
YT_START_TIME: 150

#------------------------------------
# Object detection settings
YOLO_CONFIDENCE: 0.5
YOLO_IOU_THRESHOLD: 0.5
MAX_DETECTIONS: 10

#------------------------------------
# Output video settings
# Set fullscreen. Fullscreen will override SCREEN_WIDTH and SCREEN_HEIGHT
FULLSCREEN: True

# Sets maximum pixel dimensions of the output video
# Video will be resized to fit within these dimensions
SCREEN_WIDTH: 1728
SCREEN_HEIGHT: 972

#------------------------------------
# Audio Config

BASE_FREQ: 110
AMP: 0.5