# Set to:
# VIDEO - use video file with name VIDEO_FILE
# YT - use YouTube URL with name YT_URL
# WEBCAM - use webcam

SOURCE: "YT"  # Options: "VIDEO", "YT", "WEBCAM"

VIDEO_FILE: "9MgRErd6o8w.mp4"

# example URL:
YT_URL: "https://www.youtube.com/watch?v=9MgRErd6o8w"
# Seconds into the video to start at
YT_START_TIME: 230

#------------------------------------
# Object detection settings
YOLO_CONFIDENCE: 0.5
YOLO_IOU_THRESHOLD: 0.5
MAX_DETECTIONS: 2

#------------------------------------
# Output video settings
# Sets maximum pixel dimensions of the output video
# Video will be resized to fit within these dimensions
SCREEN_WIDTH: 1728
SCREEN_HEIGHT: 972

#------------------------------------
# Audio Config

BASE_FREQ: 110
AMP: 0.5