# Set to:
# VIDEO - use video file with name VIDEO_FILE
# YT - use YouTube URL with name YT_URL
# WEBCAM - use webcam

SOURCE: "YT"  # Options: "VIDEO", "YT", "WEBCAM"

VIDEO_FILE: "templeBar.mp4"

# "https://www.youtube.com/watch?v=O0du5kMKHMk"   # Ireland
# "https://www.youtube.com/watch?v=alN1ePd2mrg" # cats
YT_URL: "https://www.youtube.com/watch?v=O0du5kMKHMk" # Ireland
YT_START_TIME: 50

#------------------------------------
# Object detection settings
YOLO_CONFIDENCE: 0.5
YOLO_IOU_THRESHOLD: 0.5
MAX_DETECTIONS: 10

#------------------------------------
# Output video settings
# Sets maximum pixel dimensions of the output video
# Video will be resized to fit within these dimensions
# Leave either empty to use the original video dimensions
SCREEN_WIDTH: 1800
SCREEN_HEIGHT: 1000

#------------------------------------
# Audio Config

BASE_FREQ: 110
AMP: 0.5